# Generated by Django 3.0.8 on 2020-08-14 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradenum', models.CharField(max_length=10, null=True)),
                ('traintype', models.CharField(max_length=20, null=True)),
                ('worktype', models.CharField(max_length=20, null=True)),
                ('trainproperty', models.CharField(max_length=20, null=True)),
                ('gradenumber', models.IntegerField()),
                ('gradestarttime', models.DateField()),
                ('traintime', models.DateField()),
                ('teachername', models.CharField(max_length=20, null=True)),
                ('examtime', models.DateField()),
                ('trainplace', models.CharField(max_length=20, null=True)),
                ('remark', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20)),
                ('gdate', models.DateTimeField()),
                ('ggirlnum', models.IntegerField()),
                ('gboynum', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Monthreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30, null=True)),
                ('contactname', models.CharField(max_length=20, null=True)),
                ('contactphone', models.CharField(max_length=20, null=True)),
                ('trainstarttime', models.DateField()),
                ('trainendtime', models.DateField()),
                ('trainproperty', models.CharField(max_length=10, null=True)),
                ('traintype', models.CharField(max_length=20, null=True)),
                ('worktype', models.CharField(max_length=20, null=True)),
                ('operatetype', models.CharField(max_length=20, null=True)),
                ('trainplace', models.CharField(max_length=20, null=True)),
                ('trainnumber', models.IntegerField()),
                ('theorytime', models.DateField()),
                ('practisetime', models.DateField()),
                ('remark1', models.CharField(max_length=30, null=True)),
                ('remark2', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('sgender', models.BooleanField()),
                ('sage', models.IntegerField()),
                ('scontend', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('sgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Grades')),
            ],
        ),
    ]
